[workspace]
members = ["web", "dog"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[profile.dev.package.sqlx-macros]
opt-level = 3

[workspace.dependencies]
log = "0.4.25"
dotenvy = "0.15.7"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"
