[package]
name = "dog"
version = "0.1.0"
edition = "2021"

[dependencies]
log.workspace = true
dotenvy.workspace = true
serde.workspace = true
serde_json.workspace = true

reqwest = { version = "0.12.7", features = ["blocking", "json"] }
serde_tuple = "1.0.0"
