[package]
name = "dog"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.25"
dotenvy = "0.15.7"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"

reqwest = { version = "0.12.7", features = ["blocking", "json"] }
serde_tuple = "1.0.0"
