[package]
name = "dog"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.7", features = ["blocking", "json"] }
dotenvy = "0.15.7"
serde = { version = "1.0.210", features = ["derive"] }
serde_tuple = "1.0.0"
serde_json = "1.0.128"
